# NAIVE Bayes alogorithm

## Introduction:
Naive Bayes is a classification algorithm based on Bayes' theorem. It is not a single algorithm but a family of algorithms where all of them share a common principle, i.e. every pair of features being classified is independent of each other.


## Bayes' Theorem:
Bayes' theorem is also known as Bayes' Rule or Bayes' law, which is used to determine the probability of a hypothesis with prior knowledge. It depends on the conditional probability.

## Conditional Probability:
Conditional probability is the probability of an event occurring, assuming that another event has already occurred. For example, if you are in a meeting, what is the probability of your phone ringing? The answer is based on the probability of your phone ringing when you are not in a meeting and the probability of you being in a meeting.

## Bayes' Theorem Formula:

$$P(A|B) = \frac{P(B|A)P(A)}{P(B)}$$
    
    where A and B are events and P(B) != 0.
    In the formula, $P(B|A)$ is called the conditional probability of event B given that event A has occurred. This means if
    $P(A)$ is the probability of event A, then $P(B|A)$ is the probability of event B given that event A has occurred.
    Similarly, $P(A|B)$ is the probability of event A given that event B has occurred.
    The denominator P(B) represents the probability of just event B occurring.
    



In [55]:
# import libraries 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB ,MultinomialNB , BernoulliNB
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [56]:
# load the data set 
iris = load_iris()
X = iris.data 
y = iris.target

#train dataset 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)


In [57]:
# model initialize 

gnb = GaussianNB()

# model training    
gnb.fit(X_train, y_train)

#predict the test data
y_pred = gnb.predict(X_test)

# model evaluation
print("Accurracy score", accuracy_score(y_test,y_pred))
print("Confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("Classification report: \n", classification_report(y_test,y_pred))






Accurracy score 0.9555555555555556
Confusion matrix: 
 [[23  0  0]
 [ 0  6  1]
 [ 0  1 14]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.86      0.86      0.86         7
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.96      0.96      0.96        45



In [58]:
# model intialize

mnb = MultinomialNB()

# model training
gnb.fit(X_train, y_train)

#predict the test data
y_pred = gnb.predict(X_test)

# model evaluation
print("Accurracy score", accuracy_score(y_test,y_pred))
print("Confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("Classification report: \n", classification_report(y_test,y_pred))




Accurracy score 0.9555555555555556
Confusion matrix: 
 [[23  0  0]
 [ 0  6  1]
 [ 0  1 14]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.86      0.86      0.86         7
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.96      0.96      0.96        45



In [59]:
# mode intialized 

bnb = BernoulliNB()


# model training
gnb.fit(X_train, y_train)

#predict the test data
y_pred = gnb.predict(X_test)

# model evaluation
print("Accurracy score", accuracy_score(y_test,y_pred))
print("Confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("Classification report: \n", classification_report(y_test,y_pred))

Accurracy score 0.9555555555555556
Confusion matrix: 
 [[23  0  0]
 [ 0  6  1]
 [ 0  1 14]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.86      0.86      0.86         7
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.96      0.96      0.96        45

